# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: "ubuntu-18.04"

stages:
# Build
  - stage: Build
    displayName: 'Build'
    jobs:
    - job: Build

    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '10.x'

    # - task: Npm@1
    #   displayName: 'npm install'
    #   inputs:
    #     workingDir: 'clock-app'
    #     command: install

    # - task: Npm@1
    #   displayName: 'npm build'
    #   inputs:
    #     workingDir: 'pmo-app'
    #     command: custom
    #     customCommand: run-script build

# - script: |
#     npm install
#     npm run build
#   displayName: 'npm install and build'

# - task: Npm@1
#       displayName: 'npm build'
#       inputs:
#         workingDir: 'pmo-app'
#         command: custom
#         customCommand: run-script build

# - task: CopyFiles@2
#   displayName: 'Copy Files'
#   inputs:
#     SourceFolder: 'clock-app\build'
#     TargetFolder: '$(build.artifactstagingdirectory)'
#     CleanTargetFolder: true

# - task: PublishBuildArtifacts@1
#   inputs:
#     pathtoPublish: $(Build.ArtifactStagingDirectory) # dist or build files
#     ArtifactName: 'www' # output artifact named www
